# Catppuccin - Mocha

format = """
[░▒▓](#cdd6f4)\
$os\
[](bg:#89b4fa fg:#cdd6f4)\
$directory\
[](fg:#89b4fa bg:#b4befe)\
$git_branch\
$git_status\
[](fg:#b4befe bg:#45475a)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#45475a bg:#313244)\
$time\
[ ](fg:#313244)\
\n$character"""

[os]
format = "[  ]($style)"
style = "bg:#cdd6f4 fg:#1e1e2e"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
# Mint = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[character]
success_symbol = ""
error_symbol = ""

[directory]
style = "fg:#45475a bg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Games" = "󰊗 "
"Videos" = "󱜏 "
"Desktop" = "󰇄 "

[git_branch]
symbol = ""
style = "bg:#b4befe"
format = '[[ $symbol $branch ](fg:#313244 bg:#b4befe)]($style)'

[git_status]
style = "bg:#b4befe"
format = '[[($all_status$ahead_behind )](fg:#313244 bg:#b4befe)]($style)'

[nodejs]
symbol = ""
style = "bg:#45475a"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#45475a)]($style)'

[rust]
symbol = ""
style = "bg:#45475a"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#45475a)]($style)'

[golang]
symbol = ""
style = "bg:#45475a"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#45475a)]($style)'

[php]
symbol = ""
style = "bg:#45475a"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#45475a)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#313244"
format = '[[  $time ](fg:#b4befe bg:#313244)]($style)'
