format = """
[░▒▓](#ddc7a1)\
$os\
[](bg:#d8a657 fg:#ddc7a1)\
$directory\
[](fg:#d8a657 bg:#e78a4e)\
$git_branch\
$git_status\
[](fg:#e78a4e bg:#4f422e)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#4f422e bg:#282828)\
$time\
[ ](fg:#282828)\
\n$character"""

[os]
format = "[  ]($style)"
style = "bg:#ddc7a1 fg:#1e1e2e"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
# Mint = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[character]
success_symbol = ""
error_symbol = ""

[directory]
style = "fg:#4f422e bg:#d8a657"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰇚 "
"Music" = "󰝚 "
"Pictures" = " "
"Games" = "󰊗 "
"Videos" = "󱜏 "
"Desktop" = "󰇄 "

[git_branch]
symbol = ""
style = "bg:#e78a4e"
format = '[[ $symbol $branch ](fg:#282828 bg:#e78a4e)]($style)'

[git_status]
style = "bg:#e78a4e"
format = '[[($all_status$ahead_behind )](fg:#282828 bg:#e78a4e)]($style)'

[nodejs]
symbol = ""
style = "bg:#4f422e"
format = '[[ $symbol ($version) ](fg:#d8a657 bg:#4f422e)]($style)'

[rust]
symbol = ""
style = "bg:#4f422e"
format = '[[ $symbol ($version) ](fg:#d8a657 bg:#4f422e)]($style)'

[golang]
symbol = ""
style = "bg:#4f422e"
format = '[[ $symbol ($version) ](fg:#d8a657 bg:#4f422e)]($style)'

[php]
symbol = ""
style = "bg:#4f422e"
format = '[[ $symbol ($version) ](fg:#d8a657 bg:#4f422e)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#282828"
format = '[[  $time ](fg:#e78a4e bg:#282828)]($style)'
