format = """
[ ](#31748f)\
$os\
[](bg:#9ccfd8 fg:#31748f)\
$directory\
[](fg:#9ccfd8 bg:#ebbcba)\
$git_branch\
$git_status\
[](fg:#ebbcba bg:#26233a)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#26233a bg:#21202e)\
$time\
[ ](fg:#21202e)\
\n$character"""

[os]
format = "[  ]($style)"
style = "bg:#31748f fg:#1e1e2e"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
# Mint = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[character]
success_symbol = " "
error_symbol = " "

[directory]
style = "fg:#191724 bg:#9ccfd8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Games" = "󰊗 "
"Videos" = "󱜏 "
"Desktop" = "󰇄 "

[git_branch]
symbol = ""
style = "bg:#ebbcba"
format = '[[ $symbol $branch ](fg:#21202e bg:#ebbcba)]($style)'

[git_status]
style = "bg:#ebbcba"
format = '[[($all_status$ahead_behind )](fg:#21202e bg:#ebbcba)]($style)'

[nodejs]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#26233a)]($style)'

[rust]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#26233a)]($style)'

[golang]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#26233a)]($style)'

[php]
symbol = ""
style = "bg:#26233a"
format = '[[ $symbol ($version) ](fg:#9ccfd8 bg:#26233a)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#21202e"
format = '[[  $time ](fg:#908caa bg:#21202e)]($style)'
