
[[language]]
name = "rust"
# For nightly version
# language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"]}

[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "java"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
auto-format = true

[[language]]
name = "php"
auto-format = true


[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
