[notebook]
dir = "~/Documents/Notes/notebook"

[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}-{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"


[group.daily]
paths = ["journal/daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "daily.md"


[group.projects]
paths = ["projects"]

[group.projects.note]
template = "project.md"


[format.markdown]
hashtags = true
colon-tags = true


[tool]
editor = "nvim"
shell = "/bin/bash"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"


[filter]
recents = "--sort created- --created-after 'last two weeks'"


[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"


[lsp]

[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
